<?php


function dbem_new_event_page() {

	$title=__("Insert New Event", 'dbem');
	$event = dbem_get_event($element);
	dbem_event_form($event, $title, $element);
	
}

function dbem_events_subpanel() {         

  global $wpdb;
	$action=$_GET['action']; 
	$action2 =$_GET['action2'];
	$event_ID=$_GET['event_id'];
	$recurrence_ID=$_GET['recurrence_id'];
	$scope=$_GET['scope']; 
	$offset=$_GET['offset'];
	$order=$_GET['order'];
	$selectedEvents = $_GET['events'];
	
	if ($order == "")
	 $order = "ASC";
	if ($offset=="")
	 $offset = "0";
	$event_table_name = $wpdb->prefix.EVENTS_TBNAME;
	// Debug code, to make sure I get the correct page


	// DELETE action
	if ($action == 'deleteEvents') {
	  //  $sql="DELETE FROM ".$event_table_name." WHERE event_id='"."$event_ID"."'";
    	
		// TODO eventual error if ID in non-existant
		//$wpdb->query($sql);
    foreach($selectedEvents as $event_ID) {
		 	dbem_delete_event($event_ID);
		}

		$events = dbem_get_events("", "future");
		dbem_events_table($events, 10,"Future events");
	}
	// UPDATE or CREATE action
	if ($action == 'update_event' || $action == 'update_recurrence') {

		$event = array();   
		$venue = array();                        
		
		$event['event_name']=$_POST[event_name]; 
		// Set event end time to event time if not valid
		// if (!_dbem_is_date_valid($event['event_end_date']))
		// 	$event['event_end_date'] = $event['event-date'];  
	  $event['event_start_date'] = $_POST[event_date];
		$event['event_end_date'] = $_POST[event_end_date];
		$event['event_start_time'] = $_POST[event_hh].":".$_POST[event_mm].":00";
		$event['event_end_time'] = $_POST[event_end_hh].":".$_POST[event_end_mm].":00";         
      $recurrence['recurrence_name'] = $event['event_name'];
		$recurrence['recurrence_start_date'] = $event['event_start_date'];
		$recurrence['recurrence_end_date'] = $event['event_end_date'];
		$recurrence['recurrence_start_time'] = $event['event_start_time'];
		$recurrence['recurrence_end_time'] = $event['event_end_time'];
		$recurrence['recurrence_id'] = $_POST[recurrence_id];          
		$recurrence['recurrence_freq'] = $_POST[recurrence_freq];
		$recurrence['recurrence_freq'] == 'weekly' 
			? $recurrence[recurrence_byday] = implode(",", $_POST['recurrence_bydays']) 
			: 	$recurrence['recurrence_byday'] = $_POST[recurrence_byday];
		$_POST['recurrence_interval'] == "" ? $recurrence['recurrence_interval'] = 1 : $recurrence['recurrence_interval'] = $_POST['recurrence_interval'];
		$recurrence['recurrence_byweekno'] = $_POST[recurrence_byweekno];
		
		
		$event['event_rsvp'] = $_POST['event_rsvp'];
    $event['event_seats'] = $_POST['event_seats']; 

		if(!_dbem_is_time_valid($event_end_time))
	 		$event_end_time = $event_time;
		
		$venue['venue_name']=$_POST[venue_name];
		$venue['venue_address']=$_POST[venue_address];
		$venue['venue_town']=$_POST[venue_town];
		$event['event_notes']=$_POST[event_notes];
		$recurrence['recurrence_notes']=$_POST[event_notes]; 
		$validation_result = dbem_validate_event($event);
		
		
		if (true) { //RESETME( $validation_result == "OK") { 
			// validation successful
			$related_venue = dbem_get_identical_venue($venue); 
			//print_r($related_venue); 
			if ($related_venue)  {
				$event['venue_id'] = $related_venue['venue_id'];
				$recurrence['venue_id'] = $related_venue['venue_id'];      
			}
			else {
				$new_venue = dbem_insert_venue($venue);
				$event['venue_id']= $new_venue['venue_id'];
			}     
			   			 		
		  if(!$event_ID && !$recurrence_ID ) {
      	// there isn't anything
		  	if ($_POST[repeated_event]) {
		  			//insert new recurrence
		  		 echo "<h2>Inserimento nuova ricorrenza:".$recurrence['recurrence_id']."- </h2>"; 	
		  			dbem_insert_recurrent_event($event,$recurrence);
		  	} else {
		  		// INSERT new event 
		  		$wpdb->insert($event_table_name, $event); 
		 			$feedback_message = __('New event successfully inserted!','dbem');  
		   	}
		  } else { 
		 		// something exists
		  	if($recurrence_ID) {  
		  		// UPDATE old recurrence
		  		echo ("<h2>Aggiornamento recurrence!!!</h2>");  
		  		$recurrence['recurrence_id'] = $recurrence_ID;
		  		print_r($recurrence); 
		  		dbem_update_recurrence($recurrence);
		  		die();
		  	} else {
		  	   // UPDATE old event
		      // unlink from recurrence in case it was generated by one
	    		$event['recurrence_id'] = null;
		  		$where['event_id'] = $event_ID;
		      $wpdb->update($event_table_name, $event, $where); 
		  		$feedback_message = __('Event','dbem')." $event_ID ".__('updated','dbem')."!";   
		  	}
	  	}
			
	   

					
				//$wpdb->query($sql); 
				echo "<div id='message' class='updated fade'>
						<p>$feedback_message</p>
					  </div>";
				$events = dbem_get_events("", "future");  
				dbem_events_table($events, 10, "Future events"); 
			} else {
			  // validation unsuccessful
			
				echo $event['name'];

				echo "<div id='message' class='error '>
						<p>".__("Ach, there's a problem here:","dbem")." $validation_result</p>
					  </div>";	
				dbem_event_form($event,"Edit event $event_ID" ,$event_ID);
				 
			}
		}  
		if ($action == 'edit_event') {
				if (!$event_ID) {
				$title=__("Insert New Event", 'dbem');
				} else {
				$title=__("Edit Event", 'dbem')." $event_ID";
				}
		 
					//$event=$wpdb->get_row($sql, ARRAY_A);
					// Enter new events and updates old ones
					// DEBUG: echo"Nome: $event->event_name";

					$event = dbem_get_event($event_ID);
					dbem_event_form($event, $title, $event_ID);
				    
	  }
	 	if ($action == 'edit_recurrence') {
				
				$title=__("Edit recurrence", 'dbem');
				$event_ID = $_GET['recurrence_id'];
		 
					//$event=$wpdb->get_row($sql, ARRAY_A);
					// Enter new events and updates old ones
					// DEBUG: echo"Nome: $event->event_name";

					$recurrence = dbem_get_recurrence($event_ID);
					print_r($recurrence);
					dbem_event_form($recurrence, $title, $event_ID);
				    
	  }
	  
		if ($action == 'update_recurrence') {  
			print_r($recurrence);
			die('update recurrence!');
		}
	
	 if ($action == "-1" || $action ==""){
			// No action, only showing the events list

				
			 
			switch ($scope) {
				case "past":
					$title = __('Past Events','dbem');
					break;
				case "all":
					$title = __('All Events','dbem'); 
					break;
			  default:
					$title = __('Future Events','dbem'); 
					$scope = "future";   
			}
		  $limit = 20;
		  $events = dbem_get_events($limit, $scope, $order,$offset);  
			
		  dbem_events_table($events, $limit, $title);
			
	}
	
                                                
}         

// Function composing the options subpanel
function dbem_options_subpanel() {
	
   ?>
	<div class="wrap">
		<h2><?php _e('Event Manager Options','dbem'); ?></h2>
			<form id="dbem_options_form" method="post" action="options.php">
				<?php wp_nonce_field('update-options'); ?>
        <h3><?php _e('Events format', 'dbem');?></h3>   
				<table class="form-table">
 						<?php
						dbem_options_textarea('Default event list format', 'dbem_event_list_item_format', 'The format of any events in a list.<br/>Insert one or more of the following placeholders: <code>#_NAME</code>, <code>#_VENUE</code>, <code>#_ADDRESS</code>, <code>#_TOWN</code>, <code>#_NOTES</code>. Use <code>#_LINKEDNAME</code> for the event name with a link to the given event page. Use #_URL to print the event URL and make your own customised links. To insert date and time values, use <a href="http://www.php.net/manual/en/function.date.php">PHP time format characters</a>  with a # symbol before them, i.e. #m. #M, #j, etc.  Use HTML tags as <code>li</code>, <code>br</code>, etc.');
						dbem_options_input_text('Single event page title format', 'dbem_event_page_title_format', 'The format of a single event page title. Follow the previous formatting instructions.');
						dbem_options_textarea('Default single event format','dbem_single_event_format','The format of a single eventy page.<br/>Follow the previous formatting instructions. Use <code>#_MAP</code> to insert a map.');
						dbem_options_radio_binary('Show events page in lists?', 'dbem_list_events_page', 'Check this option if you want the events page to appear together with other pages in pages lists.');
						dbem_options_input_text('Events page title','dbem_events_page_title','The title on the multiple events page.');
						dbem_options_input_text('No events message', 'dbem_no_events_message','The message displayed when no events are available.');
						dbem_options_input_text('RSS main title','dbem_rss_main_title','The main title of your RSS events feed.');
						dbem_options_input_text('RSS main description','dbem_rss_main_description','The main description of your RSS events feed.');
						dbem_options_input_text('RSS title format','dbem_rss_title_format','The format of the title of each item in the events RSS feed.');
						dbem_options_input_text('RSS description format','dbem_rss_description_format','The format of the description of each item in the events RSS feed. Follow the previous formatting instructions.');
						?>
			</table> 
			   
			<h3><?php _e('Venues format', 'dbem');?></h3>   
				<table class="form-table">
						<tr valign="top">
							<th scope="row"><?php _e('Single venue page title format','dbem');?></th>
							<td>
								<input name="dbem_venue_page_title_format" type="text" id="dbem_venue_page_title_format" style="width: 95%" value="<?php echo get_option('dbem_venue_page_title_format'); ?>" size="45" /><br />
								<?php _e('The format of a single venue page title.','dbem')?><br/>
								<?php _e('Follow the previous formatting instructions.','dbem')?>
							</td>
						</tr>
						<tr valign="top">
							<th scope="row"><?php _e('Default single venue page format','dbem')?></th>
							<td><textarea name="dbem_single_venue_format" id="dbem_single_venue_format" rows="6" cols="60"><?php echo (get_option('dbem_single_venue_format'));?></textarea><br/>
								<?php _e('The format of a single venue page.','dbem')?><br/>
								<?php _e('Insert one or more of the following placeholders: <code>#_NAME</code>, <code>#_ADDRESS</code>, <code>#_TOWN</code>, <code>#_INFO</code>.','dbem')?><br/>  
								<?php _e('Use HTML tags as <code>li</code>, <code>br</code>, etc.','dbem')?></td>
						</tr>
					</table>
				
			<h3><?php _e('Maps and geotagging', 'dbem');?></h3>
				<table class='form-table'> 
				    <?php $gmap_is_active = get_option('dbem_gmap_is_active'); ?>
					 
				   	<tr valign="top">
				   		<th scope="row"><?php _e('Enable Google Maps integration?','dbem'); ?></th>
				   		<td>
							<input id="dbem_gmap_is_active_yes" name="dbem_gmap_is_active" type="radio" value="1" <?php if($gmap_is_active) echo "checked='checked'"; ?> /><?php _e('Yes'); ?> <br />
							<input name="dbem_gmap_is_active" type="radio" value="0" <?php if(!$gmap_is_active) echo "checked='checked'"; ?> /> <?php _e('No'); ?>  <br />
							<?php _e('Check this option to enable Goggle Map integration.','dbem')?>
						</td>
				   	</tr>
						
				   	<tr valign="top">
						<th scope="row"><?php _e('Google Maps API Key','dbem'); ?></th>
						<td>
							<input name="dbem_gmap_key" type="text" id="dbem_gmap_key" style="width: 95%" value="<?php echo get_option('dbem_gmap_key'); ?>" size="45" /><br />
									<?php _e("To display Google Maps you need a Google Maps API key. Don't worry, it's free, you can get one", "dbem");?> <a href="http://code.google.com/apis/maps/signup.html"><?php _e("here",'dbem')?></a>.
						</td>
					</tr>
					<tr valign="top">
						<th scope="row"><?php _e('Map text format','dbem')?></th>
						<td><textarea name="dbem_map_text_format" id="dbem_map_text_format" rows="6" cols="60"><?php echo (get_option('dbem_map_text_format'));?></textarea><br/>
							<?php _e('The format the text appearing in the map cloud.','dbem')?><br/>
							<?php _e('Follow the previous formatting instructions.','dbem')?></td>
					</tr>                    
				</table>
				
				<h3><?php _e('RSVP and bookings', 'dbem');?></h3>
					<?php $rsvp_is_active = get_option('dbem_rsvp_is_active'); ?>   
					<?php $rsvp_mail_notify_is_active = get_option('dbem_rsvp_mail_notify_is_active'); ?> 
					<table class='form-table'> 
          	<tr valign="top">
					  	<th scope="row"><?php _e('Enable the RSVP feature?','dbem'); ?></th>
					   	<td>
								<input id="dbem_rsvp_is_active_yes" name="dbem_rsvp_is_active" type="radio" value="1" <?php if($rsvp_is_active) echo "checked='checked'"; ?> /><?php _e('Yes'); ?> <br />
								<input name="dbem_rsvp_is_active" type="radio" value="0" <?php if(!$rsvp_is_active) echo "checked='checked'"; ?> /> <?php _e('No'); ?>  <br />
								<?php _e('Check this option to enable the RSVP feature.','dbem')?>
							</td>
					  </tr> 
						<tr valign="top">
					  	<th scope="row"><?php _e('Enable the RSVP e-mail notifications?','dbem'); ?></th>
					   	<td>
								<input id="dbem_rsvp_mail_notify_is_active_yes" name="dbem_rsvp_mail_notify_is_active" type="radio" value="1" <?php if($rsvp_mail_notify_is_active) echo "checked='checked'"; ?> /><?php _e('Yes'); ?> <br />
								<input name="dbem_rsvp_mail_notify_is_active" type="radio" value="0" <?php if(!$rsvp_mail_notify_is_active) echo "checked='checked'"; ?> /> <?php _e('No'); ?>  <br />
								<?php _e('Check this option if you want to receive an email when someone books places for your events.','dbem')?>
							</td>
					  </tr>
            <tr valign="top">
							<th scope="row"><?php _e('SMTP username','dbem'); ?></th>
							<td>
								<input name="dbem_smtp_username" type="text" id="dbem_smtp_username" style="width: 95%" value="<?php echo get_option('dbem_smtp_username'); ?>" size="45" /><br />
										<?php _e("Insert the username to be used to access your SMTP server",'dbem')?>.
							</td>
						</tr>
						<tr valign="top">
							<th scope="row"><?php _e('SMTP password','dbem'); ?></th>
							<td>
								<input name="dbem_smtp_password" type="password" id="dbem_smtp_password" style="width: 95%" value="<?php echo get_option('dbem_smtp_password'); ?>" size="45" /><br />
										<?php _e("Insert the password to be used to access your SMTP server",'dbem')?>.
							</td>
						</tr>
						<tr valign="top">
							<th scope="row"><?php _e('Notification sender address','dbem'); ?></th>
							<td>
								<input name="dbem_mail_sender_address" type="text" id="dbem_mail_sender_address" style="width: 95%" value="<?php echo get_option('dbem_mail_sender_address'); ?>" size="45" /><br />
										<?php _e("Insert the address of the notification sender. It must corresponds with your gmail account user",'dbem')?></a>.
							</td>
						</tr>
						<tr valign="top">
							<th scope="row"><?php _e('Notification receiver address','dbem'); ?></th>
							<td>
								<input name="dbem_mail_receiver_address" type="text" id="dbem_mail_receiver_address" style="width: 95%" value="<?php echo get_option('dbem_mail_receiver_address'); ?>" size="45" /><br />
										<?php _e("Insert the address of the receiver of your notifications",'dbem')?>.
							</td>
						</tr>
						   
					</table>
				
				 	<h3><?php _e('Images size', 'dbem');?></h3>
				    <table class='form-table'> 
	          	<tr valign="top">
								<th scope="row"><?php _e('Maximum width (px)','dbem'); ?></th>
								<td>
									<input name="dbem_image_max_width" type="text" id="dbem_image_max_width" style="width: 95%" value="<?php echo get_option('dbem_image_max_width'); ?>" size="45" /><br />
											<?php _e("The maximum allowed width for images uploades",'dbem')?>.
								</td>
							</tr>
							<tr valign="top">
								<th scope="row"><?php _e('Maximum height (px)','dbem'); ?></th>
								<td>
									<input name="dbem_image_max_height" type="text" id="dbem_image_max_height" style="width: 95%" value="<?php echo get_option('dbem_image_max_height'); ?>" size="45" /><br />
											<?php _e("The maximum allowed width for images uploaded, in pixels",'dbem')?>.
								</td>
							</tr>
							<tr valign="top">
								<th scope="row"><?php _e('Maximum size (bytes)','dbem'); ?></th>
								<td>
									<input name="dbem_image_max_size" type="text" id="dbem_image_max_size" style="width: 95%" value="<?php echo get_option('dbem_image_max_size'); ?>" size="45" /><br />
											<?php _e("Insert the address of the notification sender. It must corresponds with your gmail account user",'dbem')?></a>.
								</td>
							</tr>
					 </table> 
				
				
				
				<p class="submit">
					<input type="submit" id="dbem_options_submit" name="Submit" value="<?php _e('Save Changes') ?>" />
				</p>
				<input type="hidden" name="action" value="update" />
				<input type="hidden" name="page_options" value="dbem_use_event_end, dbem_event_list_item_format,dbem_event_page_title_format,dbem_single_event_format,dbem_list_events_page,dbem_events_page_title, dbem_no_events_message, dbem_venue_page_title_format, dbem_single_venue_format, dbem_gmap_is_active, dbem_rss_main_title, dbem_rss_main_description, dbem_rss_title_format, dbem_rss_description_format, dbem_gmap_key, dbem_map_text_format, dbem_rsvp_is_active, dbem_rsvp_mail_notify_is_active, dbem_smtp_username, dbem_smtp_password, dbem_mail_sender_address, dbem_mail_receiver_address, dbem_image_max_width, dbem_image_max_height, dbem_image_max_size" />
				
				
			</form>
		</div> 
	<?php

    
}




//This is the content of the event page
function dbem_events_page_content() {
	global $wpdb;
	if (isset($_REQUEST['venue_id']) && $_REQUEST['venue_id'] |= '') {
		$venue= dbem_get_venue($_REQUEST['venue_id']);
		$single_venue_format = get_option('dbem_single_venue_format');  
		$page_body = dbem_replace_venues_placeholders($single_venue_format, $venue);
	  	return $page_body;
	
	}
	if (isset($_REQUEST['event_id']) && $_REQUEST['event_id'] != '') { 
		// single event page
		$event_ID=$_REQUEST['event_id'];
		$event= dbem_get_event($event_ID);
		$single_event_format = get_option('dbem_single_event_format');  
		$page_body = dbem_replace_placeholders($single_event_format, $event);
	  	return $page_body;
	} elseif (isset($_REQUEST['calendar_day']) && $_REQUEST['calendar_day'] != ''){ 
			
			$date = $_REQUEST['calendar_day'];
			$events_N = dbem_events_count_for($date);
			// $_GET['scope'] ? $scope = $_GET['scope']: $scope =  "future";   
			// $stored_format = get_option('dbem_event_list_item_format');
			// $events_body  =  dbem_get_events_list(10, $scope, "ASC", $stored_format, $false);  
			if ($events_N > 1) {
					$_GET['calendar_day'] ? $scope = $_GET['calendar_day']: $scope =  "future";   
					$stored_format = get_option('dbem_event_list_item_format');
					$events_body  =  dbem_get_events_list(10, $scope, "ASC", $stored_format, $false); 
					return $events_body;   
			} else {
			   $events = dbem_get_events("",$_REQUEST['calendar_day']);
				  $event= $events[0];
					$single_event_format = get_option('dbem_single_event_format');  
					$page_body = dbem_replace_placeholders($single_event_format, $event);
				  return $page_body;
			}
			return $events_body;
	} else { 
		// Multiple events page
		$_GET['scope'] ? $scope = $_GET['scope']: $scope =  "future";   
		$stored_format = get_option('dbem_event_list_item_format');
		$events_body  =  dbem_get_events_list(10, $scope, "ASC", $stored_format, $false);  
		return $events_body;       
		
	}
}                                                         
function dbem_events_count_for($date) {
	global $wpdb;      
	$table_name = $wpdb->prefix .EVENTS_TBNAME;           
	$sql = "SELECT COUNT(*) FROM  $table_name WHERE event_start_date  like '$date';";
	return $wpdb->get_var($sql);
}

// filter function to call the event page when appropriate
function dbem_filter_events_page($data) {
	
	// $table_name = $wpdb->prefix .EVENTS_TBNAME;
	// 	$start = strpos($data, DBEM_PAGE);
	
	$is_events_post = (get_the_ID() == get_option('dbem_events_page'));
 	$events_page_id = get_option('dbem_events_page');      
    if (is_page($events_page_id) && $is_events_post) { 
	    return dbem_events_page_content();
	} else {
		return $data;
	} 
}
add_filter('the_content','dbem_filter_events_page');

function dbem_events_page_title($data) {
	$events_page_id = get_option('dbem_events_page');
	$events_page = get_page($events_page_id);
	$events_page_title = $events_page->post_title;      


	if (($data == $events_page_title) && (is_page($events_page_id))) {
		if (isset($_REQUEST['venue_id']) && $_REQUEST['venue_id'] |= '') {
			$venue= dbem_get_venue($_REQUEST['venue_id']);
			$stored_page_title_format = get_option('dbem_venue_page_title_format');
			$page_title = dbem_replace_venues_placeholders($stored_page_title_format, $venue);
			return $page_title;
		}
	   	if (isset($_REQUEST['event_id']) && $_REQUEST['event_id'] != '') { 
			// single event page
			$event_ID=$_REQUEST['event_id'];
			$event= dbem_get_event($event_ID);
			$stored_page_title_format = get_option('dbem_event_page_title_format');
			$page_title = dbem_replace_placeholders($stored_page_title_format, $event);
			return $page_title;
			} else { 
			// Multiple events page
		  $page_title = get_option('dbem_events_page_title');  
			return $page_title;       

		}
	
	} else {
		return $data;
	}                
	
} 
// to make sure that in pages lists the title is dbem_events_page_title, and not overwritten by the previous filter
add_filter('the_title','dbem_events_page_title');  
add_filter('single_post_title','dbem_events_page_title');   

function dbem_filter_get_pages($data) {
	$output = array();
    $events_page_id = get_option('dbem_events_page');
	for ($i = 0; $i < count($data); ++$i) {  
		if ($data[$i]->ID == $events_page_id) {   
			$list_events_page = get_option('dbem_list_events_page');
			if($list_events_page) {
				$data[$i]->post_title = get_option('dbem_events_page_title')."&nbsp;";  
		    	$output[] = $data[$i];
			} 
		} else {
	    	$output[] = $data[$i];
	   }
   } 
   return $output; 
}                                  
add_filter('get_pages', 'dbem_filter_get_pages');
            


//
// TODO: ROBA NUOVA DA RIORDINARE
// ADMIN CSS for debug
function dbem_admin_css() {
	$css = "
	<style type='text/css'>
	.debug{
		color: green;
		background: #B7F98C;
		margin: 15px;
		padding: 10px;
		border: 1px solid #629948;
	}
	.switch-tab {
		background: #aaa;
		width: 100px;
		float: right;
		text-align: center;
		margin: 3px 1px 0 5px;
		padding: 2px;
	}
	.switch-tab a {
		color: #fff;
		text-decoration: none;
	}
	.switch-tab a:hover {
		color: #D54E21;
		
	} 
	#events-pagination {
		text-align: center; 
		
	}
	#events-pagination a {
		margin: 0 20px 0 20px;
		text-decoration: none;
		width: 80px;
		padding: 3px 0; 
		background: #FAF4B7;
		border: 1px solid #ccc;
		border-top: none;
	} 
	#new-event {
		float: left;
	 
	}
	</style>";
	echo $css;
}

add_action('admin_print_scripts','dbem_admin_css');

// exposed function, for theme  makers
function dbem_get_events_list($limit="3", $scope="future", $order="ASC", $format='', $display=true) {
	if ($scope == "") 
		$scope = "future";
	if ($order != "DESC") 
		$order = "ASC";	
	if ($format == '')
		$format = get_option('dbem_event_list_item_format');
	$events = dbem_get_events($limit, $scope, $order);
	$output = "";
	if (!empty($events)) {
	foreach ($events as $event){
	  //  $localised_date = mysql2date("j M Y", $event->event_time);

	 	
			
		$output .= dbem_replace_placeholders($format, $event);
	}
	} else {
		$output = "<li class='dbem-no-events'>".get_option('dbem_no_events_message')."</li>";
	}
	if ($display)
		echo $output;
	else
		return $output;
}  

function dbem_get_events_page($justurl=false, $display=true) {
	$page_link = get_permalink(get_option("dbem_events_page")) ;
	if($justurl) {  
		$result = $page_link;
	} else {
		$page_title = get_option("dbem_events_page_title") ;
		$result = "<a href='$page_link' title='$page_title'>$page_title</a>";
	}
	if ($display)
		echo $result;
	else
		return $result;
	
}       

// TEMPLATE TAGS

function dbem_are_events_available($scope="future") {
	if ($scope == "") 
		$scope = "future";
	$events = dbem_get_events(1, $scope);    
	
  	if (empty($events))
		return FALSE;
  	else 
		return TRUE  ;
}
	
// Returns true if the page in question is the events page
function dbem_is_events_page() {
	$events_page_id = get_option('dbem_events_page');
	return is_page($events_page_id);
}    

function dbem_is_single_event_page() {
	return  (dbem_is_events_page() && (isset($_REQUEST['event_id']) && $_REQUEST['event_id'] != '')) ;
}

function dbem_is_multiple_events_page() {
	return  (dbem_is_events_page() && !(isset($_REQUEST['event_id']) && $_REQUEST['event_id'] != '')) ;
}


// main function querying the database event table
function dbem_get_events($limit="",$scope="future",$order="ASC", $offset="") {
	global $wpdb;   
	
 	$events_table = $wpdb->prefix.EVENTS_TBNAME;
	if ($limit != "")
		$limit = "LIMIT $limit";
	if ($offset != "")
		$offset = "OFFSET $offset";  
	

	$timestamp = time();
	$date_time_array = getdate($timestamp);
  $hours = $date_time_array['hours'];
	$minutes = $date_time_array['minutes'];
	$seconds = $date_time_array['seconds'];
	$month = $date_time_array['mon'];
	$day = $date_time_array['mday'];
	$year = $date_time_array['year'];
 	$today = strftime('%Y-%m-%d', mktime($hours,$minutes,$seconds,$month,$day,$year));
	
	if(preg_match("/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/", $scope)) {
		$temporal_condition = "WHERE event_start_date like '$scope'" ;
	}	 else {
	if (($scope != "past") && ($scope !="all"))
	 		$scope = "future"; 
	  if ($scope == "future") 
			$temporal_condition = "WHERE event_start_date >= '$today'" ;
		if ($scope == "past") 
			$temporal_condition = "WHERE event_start_date < '$today'" ;
		if ($scope == "all")
			$temporal_condition = "";
	}
 
	
 
	
	$sql = "SELECT event_id, 
			    event_name, 
			  	DATE_FORMAT(event_start_time, '%e') AS 'event_day',
			  	DATE_FORMAT(event_start_time, '%Y') AS 'event_year',
			  	DATE_FORMAT(event_start_time, '%k') AS 'event_hh',
			  	DATE_FORMAT(event_start_time, '%i') AS 'event_mm',
					DATE_FORMAT(event_end_time, '%e') AS 'event_end_day',
			  	DATE_FORMAT(event_end_time, '%Y') AS 'event_end_year',
			  	DATE_FORMAT(event_end_time, '%k') AS 'event_end_hh',
			  	DATE_FORMAT(event_end_time, '%i') AS 'event_end_mm',
			  	event_start_date,
					event_end_date,
					event_start_time,
					event_end_time,
	 				event_notes, 
					event_rsvp,
					recurrence_id, 
					venue_id 
					FROM $events_table   
					$temporal_condition
					ORDER BY event_start_date $order
					$limit 
					$offset";   
    
  $wpdb->show_errors = true;
	$events = $wpdb->get_results($sql, ARRAY_A); 
	if (!empty($events)) {
		//$wpdb->print_error(); 
		$inflated_events = array();
		foreach($events as $this_event) {
		
			$this_venue = dbem_get_venue($this_event['venue_id']);
			$this_event['venue_name'] = $this_venue['venue_name'];
			$this_event['venue_address'] = $this_venue['venue_address'];
			$this_event['venue_town'] = $this_venue['venue_town'];
			array_push($inflated_events, $this_event);
		}
	  
		return $inflated_events;
	} else {
		return null;
	}
}    
function dbem_get_event($event_id) {
	global $wpdb;
	$events_table = $wpdb->prefix.EVENTS_TBNAME; 	
	$sql = "SELECT event_id, 
			   	event_name, 
		 	  	DATE_FORMAT(event_start_date, '%Y-%m-%e') AS 'event_date', 
					DATE_FORMAT(event_start_date, '%e') AS 'event_day',   
					DATE_FORMAT(event_start_date, '%m') AS 'event_month',
					DATE_FORMAT(event_start_date, '%Y') AS 'event_year',
			  	DATE_FORMAT(event_start_time, '%k') AS 'event_hh',
			  	DATE_FORMAT(event_start_time, '%i') AS 'event_mm', 
			    DATE_FORMAT(event_end_time, '%Y-%m-%e') AS 'event_end_date', 
					DATE_FORMAT(event_end_time, '%e') AS 'event_end_day',        
					DATE_FORMAT(event_end_time, '%m') AS 'event_end_month',  
		  		DATE_FORMAT(event_end_time, '%Y') AS 'event_end_year',
		  		DATE_FORMAT(event_end_time, '%k') AS 'event_end_hh',
		  		DATE_FORMAT(event_end_time, '%i') AS 'event_end_mm',   
		      event_start_date,
					event_end_date,
					event_start_time,
			  	event_end_time,
					event_notes,
					event_rsvp,
					event_seats,
					recurrence_id, 
					venue_id
				FROM $events_table   
			    WHERE event_id = $event_id";   
	     
	//$wpdb->show_errors(true);
	$event = $wpdb->get_row($sql,ARRAY_A);	
	//$wpdb->print_error();
	$venue = dbem_get_venue($event['venue_id']); 
	$event['venue_name'] = $venue['venue_name'];
	$event['venue_address'] = $venue['venue_address'];
	$event['venue_town'] = $venue['venue_town'];   
	$event['venue_image_url'] = $venue['venue_image_url'];
	return $event;
}        


function dbem_events_table($events, $limit, $title) {	
	if (isset($_GET['scope'])) 
		$scope = $_GET['scope'];
 	else
		$scope = "future";
	if (($scope  != "past") && ($scope != "all"))
		$scope = "future";
	$events_count = count(dbem_get_events("",$scope));
	
	if (isset($_GET['offset'])) 
		$offset = $_GET['offset'];
	
	$use_events_end = get_option('dbem_use_event_end');
		
	?>
	 
	<div class="wrap">
		  
		 <h2><?php echo $title; ?></h2>   
  	<!--<div id='new-event' class='switch-tab'><a href="<?php bloginfo('wpurl')?>/wp-admin/edit.php?page=events-manager/events-manager.php&amp;action=edit_event"><?php _e('New Event ...', 'dbem');?></a></div>-->  
		<?php
			
			$link = array();
			$link['past'] = "<a href='".get_bloginfo('url')."/wp-admin/edit.php?page=events-manager/events-manager.php&amp;scope=past&amp;order=desc'>".__('Past events','dbem')."</a>"; 
			$link['all'] = " <a href='".get_bloginfo('url')."/wp-admin/edit.php?page=events-manager/events-manager.php&amp;scope=all&amp;order=desc'>".__('All events','dbem')."</a>";   
			$link['future'] = "  <a href='".get_bloginfo('url')."/wp-admin/edit.php?page=events-manager/events-manager.php&amp;scope=future'>".__('Future events','dbem')."</a>";  
			
			$scope_names = array();
			$scope_names['past'] = __('Past events','dbem'); 
	    $scope_names['all'] = __('All events','dbem');
			$scope_names['future'] = __('Future events','dbem');
			
			 ?> 
		
  			<form id="posts-filter" action="" method="get">
        <input type='hidden' name='page' value='events-manager/events-manager.php'/>  
				<ul class="subsubsub">
				<li><a href='edit.php'  class="current">Totale <span class="count">(<?php echo (count($events));?>)</span></a> |</li>
				<li><a href='edit.php?post_status=publish' >Pubblicato <span class="count">(1)</span></a></li></ul>


				<div class="tablenav">

				<div class="alignleft actions">
				<select name="action">
        <option value="-1" selected="selected"><?php _e('Bulk Actions');?></option> 	
				<option value="deleteEvents" "><?php _e('Delete selected');?></option> 
				
				</select>
				<input type="submit" value="Applica" name="doaction2" id="doaction2" class="button-secondary action" />
				<select name="scope">
	
					<?php
					foreach ($scope_names as $key => $value) {
						$selected = "";
						if ($key == $scope) 
							$selected = "selected='selected'";
					  echo "<option value='$key' $selected>$value</option>  ";
					}       
					?>
				</select>	
				<input id="post-query-submit" class="button-secondary" type="submit" value="<?php _e('Filter')?>"/>
				</div>
				<div class="clear"></div>
				</div>
				<?php 
				if (empty($events)) {
					 // TODO localize
					echo "no events";
				} else {
					?>
		
	<table class="widefat">
  		<thead>
			<tr>
  				<th class='manage-column column-cb check-column' scope='col'>&nbsp;</th>
  	  		<th><?php _e('Name', 'dbem');?></th>
  	   		<th><?php _e('Venue', 'dbem');?></th>
  	   	 
  	  
				<th colspan="2"><?php _e('Date and time', 'dbem');?></th>
  	  	
	
  	   		
  	  </tr>
			</thead>
			<tbody>
  	  <?php
  		$i =1;
  		foreach ($events as $event){
  			$class = ($i % 2) ? ' class="alternate"' : '';
				// FIXME set to american
				$localised_date = mysql2date(__('D d M Y'), $event['event_start_date']);
  			$style = "";
  		 	$today = date("Y-m-d");
 
			  $venue_summary = "<b>".$event['venue_name']."</b><br/>".$event['venue_address']." - ".$event['venue_town'];
				
			  
				if ($event['event_start_date'] < $today )
					$style= "style ='background-color: #FADDB7;'";
			?>
	  <tr <?php echo"$class $style"; ?> >   
			 
  	   <td>
 	    		<input type='checkbox' value='<?php echo $event['event_id'];?>' name='events[]'/></td>
  	   </td>
  	   <td>
  	    <strong><a class="row-title" href="<?php bloginfo('wpurl')?>/wp-admin/edit.php?page=events-manager/events-manager.php&amp;action=edit_event&amp;event_id=<?php echo $event['event_id']; ?>"><?php echo ($event['event_name']); ?></a></strong>
  	   </td>
  	   <td>
  	 
				 <?php echo $venue_summary; ?>
				
  	   </td>
  	  
		<td>
  	     <?php echo $localised_date ; ?><br/>
  	    
  	     <?php echo substr($event['event_start_time'],0,5)." - ".substr($event['event_end_time'],0,5) ; ?>
		</td>
		<td>
				 <?php if($event['recurrence_id']) {
								$recurrence = dbem_get_recurrence($event[recurrence_id]);   ?>
						
								<b><a href="<?php bloginfo('wpurl')?>/wp-admin/edit.php?page=events-manager/events-manager.php&amp;action=edit_recurrence&amp;recurrence_id=<?php echo $recurrence['recurrence_id'];?>"><?php echo $recurrence['recurrence_description'];?></a></b>
								
								 
							 <?php } ?>
  	    </td>
	 
	   
	<?php
  	    	   echo'</tr>'; 
  	   $i++;
		}
	    ?>
	   
			</tbody>
  	  </table>  
  <?php } // end of table?>

			<div class='tablenav'>
				<div class=alignleft actions>
				
			 	 
					<br class='clear'/> 
				</div>
				<br class='clear'/>
				</div>
			</form>
		</div>
	</div>  

 			<?php
 			if ($events_count >  $limit) {
				$backward = $offset + $limit;
				$forward = $offset - $limit; 
				if (DEBUG)
			 		echo "COUNT = $count BACKWARD = $backward  FORWARD = $forward<br> -- OFFSET = $offset" ; 
				echo "<div id='events-pagination'> ";
				if ($backward < $events_count)
					echo "<a style='float: left' href='".get_bloginfo('url')."/wp-admin/edit.php?page=eventmanager.php&amp;scope=$scope&offset=$backward'>&lt;&lt;</a>" ;
				if ($forward >= 0)
					echo "<a style='float: right' href='".get_bloginfo('url')."/wp-admin/edit.php?page=eventmanager.php&amp;scope=$scope&offset=$forward'>&gt;&gt;</a>";
		    echo "</div>" ;
		}
			?>
			
	</div>
<?php
}
function dbem_event_form($event, $title, $element) { 
	
	global $localised_date_formats;
	// change prefix according to event/recurrence
	$_GET['action'] == "edit_recurrence" ? $pref = "recurrence_" : $pref = "event_";
	
	$_GET['action'] == "edit_recurrence" 
	? $form_destination=  "edit.php?page=events-manager/events-manager.php&amp;action=update_recurrence&amp;recurrence_id=".$element  
	: $form_destination = "edit.php?page=events-manager/events-manager.php&amp;action=update_event&amp;event_id=".$element;

	
	$locale_code = substr(get_locale(), 0, 2); 
	$localised_date_format = $localised_date_formats[$locale_code];
	$localised_example = str_replace("yy", "2008", str_replace("mm", "11", str_replace("dd", "28", $localised_date_format))); 
	$localised_end_example = str_replace("yy", "2008", str_replace("mm", "11", str_replace("dd", "28", $localised_date_format)));
	
	if ($event[$pref.'start_date'] != "") {
		preg_match("/(\d{4})-(\d{2})-(\d{2})/",$event[$pref.'start_date'], $matches );
		$year = $matches[1];
		$month = $matches[2];
		$day = $matches[3]; 
		$localised_date = str_replace("yy", $year, str_replace("mm", $month, str_replace("dd", $day, $localised_date_format)));  
	} else {
		$localised_date = "";
	}
	if ($event[$pref.'end_date'] != "") {  
		preg_match("/(\d{4})-(\d{2})-(\d{2})/",$event[$pref.'end_date'], $matches );
		$end_year = $matches[1];
		$end_month = $matches[2];
		$end_day = $matches[3];
	   $localised_end_date = str_replace("yy", $end_year, str_replace("mm", $end_month, str_replace("dd", $end_day, $localised_date_format)));
	} else {
		$localised_end_date = "";
	}    
	// if($event[$pref.'rsvp'])
	// 	echo (dbem_bookings_table($event[$pref.'id']));      
		
		
	$freq_options = array("daily" => __('Daily', 'dbem'), "weekly" => __('Weekly','dbem'),"monthly" => __('Monthly','dbem'));    
	$days_names = array(1 => __('Mon'), 2 => __('Tue'), 3 =>__('Wed'), 4 =>__('Thu'), 5 =>__('Fri'), 6 =>__('Sat'), 7 =>__('Sun'));
 	$saved_bydays = explode(",", $event['recurrence_byday']);
	$weekno_options = array("1" => __('first', 'dbem'), '2' => _('second','dbem'),'3'=>__('third','dbem'),'4'=>__('fourth', 'dbem'), '-1'=>__('last','dbem'));
	
	$event[$pref.'rsvp'] ? $event_RSVP_checked = "checked='checked'" :  $event_RSVP_checked ='';
	
	?> 
<form id="eventForm" method="post" action="<?php echo $form_destination; ?>">
    <div class="wrap">
		<h2><?php echo $title; ?></h2>
   		<div id="poststuff" class="metabox-holder">
        

				<!-- SIDEBAR -->	
			 	<div id="side-info-column" class="inner-sidebar">  
					<div id='side-sortables' class='meta-box-sortables'>
	          		<!-- recurrence postbox -->
						<div id="submitdiv" class="postbox " >
							<div class="handlediv" title="Fare clic per cambiare."><br /></div>
							<h3 class='hndle'><span>Recurrence</span></h3>
							
							<div class="inside">     
                        <?php
                        if(!$event['event_id']) {
                        ?>
								<?php if($event['recurrence_id'] != "") 
												$recurrence_YES = "checked='checked'";


								?>
								<p><input id="event-recurrence" type="checkbox" name="repeated_event" value="1" <?php echo $recurrence_YES;?> /> <?php _e('Repeated event', 'dbem');?></p>  
								<div id="event_recurrence_pattern">
								<p>Frequency:
									 	<select id="recurrence-frequency" name="recurrence_freq">
									      <?php dbem_option_items($freq_options, $event[$pref.'freq']); ?>
				          </select></p>
				 					<p>
										<?php _e('Every', 'dbem')?> 
										<input id="recurrence-interval" name='recurrence_interval' size='2' value='<?php echo $event['recurrence_interval'];?>'></input> 
										<span class='interval-desc' id="interval-daily-singular"><?php _e('day', 'dbem') ?></span>
										<span class='interval-desc' id="interval-daily-plural"><?php _e('days', 'dbem') ?></span>
										<span class='interval-desc' id="interval-weekly-singular"><?php _e('week', 'dbem') ?></span>
										<span class='interval-desc' id="interval-weekly-plural"><?php _e('weeks', 'dbem') ?></span>
										<span class='interval-desc' id="interval-monthly-singular"><?php _e('month', 'dbem') ?></span>
										<span class='interval-desc' id="interval-monthly-plural"><?php _e('months', 'dbem') ?></span>  
									</p>

									<p class="alternate-selector" id="weekly-selector">
										<?php dbem_checkbox_items('recurrence_bydays[]', $days_names, $saved_bydays); ?>
									</p>   

									<p class="alternate-selector" id="monthly-selector">
									<?php _e('Every','dbem')?> 
									<select id="monthly-modifier" name="recurrence_byweekno">
										<?php dbem_option_items($weekno_options, $event['recurrence_byweekno']);?>   
						      </select>
									<select id="recurrence-weekday" name="recurrence_byday">
						       	  <?php dbem_option_items($days_names, $event['recurrence_byday']); ?>  
		              </select>&nbsp;
								</p>	
		            </div>
							 <p id="recurrence-tip"><?php _e('Check if your event happens more than once according to a regular pattern', 'dbem') ?></p>
							
							<?php } else {
								   	
										if(!$event['recurrence_id']) {   
											echo "<p>".__('This is\'t a recurrent event','dbem').".</p>";
										} else {      
											
											$recurrence = dbem_get_recurrence($event['recurrence_id']);  ?>
											<p><a href="<?php bloginfo('wpurl')?>/wp-admin/edit.php?page=events-manager/events-manager.php&amp;action=edit_recurrence&amp;recurrence_id=<?php echo $recurrence['recurrence_id'];?>"><?php echo $recurrence['recurrence_description'];?></a></p>
											
											<p><em><?php _e('If you change event data it will become an independent event') ?></em></p>
									 <?php  } ?>
								
						  <?php  } ?>
							</div>
							
							
							
						</div>
					   			
       	    	   <div id="submitdiv" class="postbox " >
							<div class="handlediv" title="Fare clic per cambiare."><br /></div>
							<h3 class='hndle'><span>RSVP</span></h3>
							<div class="inside">
								<p><input id="rsvp-checkbox" name='event_rsvp' value='1' type='checkbox' <?php echo $event_RSVP_checked ?> /> <? _e('Enable bookings for this event', 'dbem')?></p>
								<div id='rsvp-data'>
								<p>	Seats: <input id="seats-input" type="text" name="event_seats" size='5' value="<?php echo $event[$pref.'seats']?>" /><br/>
								 <?php dbem_bookings_compact_table($event[$pref.'id']);  ?>
							</div>
						</div>       
					</div>
				</div> 
			</div>
					
					
			  
				<!-- END OF SIDEBAR -->	
			
			

				<div id="post-body" class="has-sidebar">
				<div id="post-body-content" class="has-sidebar-content">
				<div id="event_name" class="stuffbox">
					<h3><?php _e('Name','dbem'); ?></h3>
					<div class="inside">
						<input type="text" name="event_name" value="<?php echo $event[$pref.'name'] ?>" /><br/>
						<?php _e('The event name. Example: Birthday party', 'dbem') ?>
					</div>
				</div>
				
				
				
				<div id="event_start_date" class="stuffbox">
					<h3><?php _e('Event dates','dbem'); ?></h3>  
					<div class="inside">
					 <input id="localised-date" type="text" name="localised_event_date" value="<?php echo $localised_date ?>" style ="display: none;" />  
					 <input id="date-to-submit" type="text" name="event_date" value="<?php echo $event[$pref.'start_date'] ?>" style="background: #FCFFAA" />              <input id="localised-end-date" type="text" name="localised_event_end_date" value="<?php echo $localised_end_date ?>" style ="display: none; " />
           
					 <input id="end-date-to-submit" type="text" name="event_end_date" value="<?php echo $event[$pref.'end_date'] ?>" style="background: #FCFFAA" />
			
			
			<br/>
						<?php _e('The event beginning and end date', 'dbem') ?>. <span id="localised_date_example" style ="display: none;"><?php echo __("Example:", "dbem")." $localised_end_example"; ?></span><span class="no-javascript-example"><?php _e("Example: 2008-11-28", "dbem")?></span> - 20:30
						
					</div>
				</div>
				

				
			
			 
					 <div id="event_end_day" class="stuffbox">
							<h3><?php _e('Event time','dbem'); ?></h3>  
							<div class="inside">
							<input type="text" size="3" maxlength="2" name="event_hh" value="<?php echo $event[$pref.'hh'] ?>" /> : <input type="text" size="3" maxlength="2" name="event_mm" value="<?php echo $event[$pref.'mm'] ?>" />
							- 
							<input type="text" size="3" maxlength="2" name="event_end_hh" value="<?php echo $event[$pref.'end_hh'] ?>" /> : <input type="text" size="3" maxlength="2" name="event_end_mm" value="<?php echo $event[$pref.'end_mm'] ?>" /><br/>
								<?php _e('The day and time of the event end', 'dbem') ?>. <span id="localised_end_example" style ="display: none;"><?php echo __("Example:", "dbem")." $localised_example"; ?></span><span class="no-javascript-example"><?php _e("Example: 2008-11-27", "dbem")?></span> - 20:30

							</div>
					 </div>
				
				
				

		
				
				 
				
						
			    <?php
				$gmap_is_active = get_option('dbem_gmap_is_active'); 
				if ($gmap_is_active) {
			 		echo "<div id='map-not-found' style='width: 450px; float: right; font-size: 140%; text-align: center; margin-top: 100px; display: hide'><p>".__('Map not found')."</p></div>";
				echo "<div id='event-map' style='width: 450px; height: 300px; background: green; float: right; display: hide; margin-right:8px'></div>";   
			}
				?>
				<div id="venue_name" class="stuffbox">
					<h3><?php _e('Venue','dbem'); ?></h3>
					<div class="inside">
						<input id="venue-name" type="text" name="venue_name" value="<?php echo $event['venue_name']?>" /><br/>
						<?php _e('The venue where the event takes place. Example: Arena', 'dbem') ?>
					</div>
				</div>
				<div id="venue_address" class="stuffbox">
					<h3><?php _e('Address','dbem'); ?></h3>
					<div class="inside">
						<input id="venue-address" type="text" name="venue_address" value="<?php echo $event['venue_address']; ?>" /><br/>
						<?php _e('The address of the venue. Example: Via Mazzini 22', 'dbem') ?>
					</div>
				</div>
				<div id="venue_town" class="stuffbox">
					<h3><?php _e('Town','dbem'); ?></h3>
					<div class="inside">
						<input id="venue-town" type="text" name="venue_town" value="<?php echo $event['venue_town']?>" /><br/>
						<?php _e('The event town. Example: Verona. If you\'re using the Google Map integration and want to avoid geotagging ambiguities include the country as well. Example: Verona, Italy', 'dbem') ?>
					</div>
				</div>
			   

				
				<div id="event_notes" class="postbox closed">
					<h3><?php _e('Notes','dbem'); ?></h3>
					<div class="inside">
						<textarea name="event_notes" rows="8" cols="60"><?php echo $event[$pref.'notes']; ?></textarea><br/>
						<?php _e('Notes about the event', 'dbem') ?>
					</div>
				</div>
			</div>
		<p class="submit"><input type="submit" name="events_update" value="<?php _e('Submit Event','dbem'); ?> &raquo;" /></p> 
		</div>
	   
	</div>  
	</div>
</form>
 <?php
}            

function dbem_validate_event($event) {
	// TODO decide which fields are required
	// Implement type check for dates, etc
	global $required_fields;
	
	foreach ($required_fields as $field) {
		if ($event[$field] == "" ) {
		return $field.__(" is missing!", "dbem");
		}       
	}
	
	$event_year = substr($event['event_date'],0,4);
	$event_month = substr($event['event_date'],5,2);
	$event_day = substr($event['event_date'],8,2);
	
	// if (!_dbem_is_date_valid($event['event_date'])) {
	// 	return __("invalid date!", "dbem");
	// }                                                         
	$time = $event['event_hh'].":".$event['event_mm'];
	$end_time = $event['event_end_hh'].":".$event['event_end_mm']; 
	// TODO re-IMPLEMENT TIME VALIDATION
	// if ( !_dbem_is_time_valid($time) ) {
	// 	return _("invalid time","dbem");
	// }   
	$use_event_end = get_option('dbem_use_event_end'); 
	if ($use_event_end && $event['event_date']." ".$time  > $event['event_end_date']." ".$end_time)
		return __("end date before begin date", "dbem");
	return "OK";
	
}

function _dbem_is_date_valid($date) {
	$year = substr($date,0,4);
	$month = substr($date,5,2);
	$day = substr($date,8,2);
	return (checkdate($month, $day, $year));
}  
function _dbem_is_time_valid($time) {  
 	$result = preg_match ("/([01]\d|2[0-3])(:[0-5]\d)/", $time);

	return ($result);
}
// Enqueing jQuery script to make sure it's loaded
function dbem_enque_scripts(){ 
	wp_enqueue_script( 'jquery' );     
	// wp_enqueue_script('datepicker','/wp-content/plugins/events-manager/jquery-ui-datepicker/jquery-ui-personalized-1.6b.js', array('jquery') );
}
add_action ('template_redirect', 'dbem_enque_scripts');

function url_exists($url) {

	if ((strpos($url, "http")) === false) $url = "http://" . $url;
    // FIXME ripristina la linea seguente e VEDI DI SISTEMARE!!!!
	// if (is_array(@get_headers($url))) {
	if (true)
       	return true;
    else
		return false;
}

// General script to make sure hidden fields are shown when containing data
function dbem_admin_general_script(){  ?>
	<script src="<?php bloginfo('url');?>/wp-content/plugins/events-manager/dbem.js" type="text/javascript"></script>  
	<script src="<?php bloginfo('url');?>/wp-content/plugins/events-manager/js/ui.datepicker.js" 	type="text/javascript"></script>

	<?php

	// Check if the locale is there and loads it
	$locale_code = substr(get_locale(), 0, 2);  

	$locale_file = get_bloginfo('url')."/wp-content/plugins/events-manager/js/i18n/ui.datepicker-$locale_code.js";
	if(url_exists($locale_file)) {   ?>
	  <script src="<?php bloginfo('url');?>/wp-content/plugins/events-manager/js/i18n/ui.datepicker-<?php echo $locale_code;?>.js" type="text/javascript"></script>   
	<?php } ?>                 
	
	
	<style type='text/css' media='all'>
		@import "<?php bloginfo('url');?>/wp-content/plugins/events-manager/js/ui.datepicker.css";
	</style>
	<script type="text/javascript">
 	//<![CDATA[        
   // TODO: make more general, to support also latitude and longitude (when added)
		$j=jQuery.noConflict();   
		
		function updateIntervalDescriptor () { 
			$j(".interval-desc").hide();
		    var number = "-plural";
			if ($j('input#recurrence-interval').val() == 1 || $j('input#recurrence-interval').val() == "")
				number = "-singular"
			var descriptor = "span#interval-"+$j("select#recurrence-frequency").val()+number;
			$j(descriptor).show();
		}
		function updateIntervalSelectors () {
			$j('p.alternate-selector').hide();   
			$j('p#'+ $j('select#recurrence-frequency').val() + "-selector").show();
			//$j('p.recurrence-tip').hide();
			//$j('p#'+ $j(this).val() + "-tip").show();
		}
		 function updateShowHideRecurrence () {
			if($j('input#event-recurrence').attr("checked")) {
			   $j("#event_recurrence_pattern").fadeIn();
			   $j("input#localised-end-date").fadeIn();
		   } else {
			   $j("#event_recurrence_pattern").hide();
			   $j("input#localised-end-date").hide();  
		   	}
		}
		
		 function updateShowHideRsvp () {
			if($j('input#rsvp-checkbox').attr("checked")) {
			   $j("div#rsvp-data").fadeIn();
			} else {
			   $j("div#rsvp-data").hide();
			}
		}
		
		$j(document).ready( function() {
			locale_format = "ciao";
	   		$j("#localised_example").show();
			$j(".no-javascript-example").hide();
			$j("#localised-date").show();
		   
			$j("#date-to-submit").hide();
			$j("#end-date-to-submit").hide(); 
			$j("#localised-date").datepicker($j.extend({},
		  		($j.datepicker.regional["it"], 
				{altField: "#date-to-submit", 
				altFormat: "yy-mm-dd"})));
	 	  	$j("#localised-end-date").datepicker($j.extend({},
		  		($j.datepicker.regional["it"], 
		  		{altField: "#end-date-to-submit", 
		  		altFormat: "yy-mm-dd"})));
		     

		   updateIntervalDescriptor(); 
		   updateIntervalSelectors();
		   updateShowHideRecurrence();  
		   updateShowHideRsvp();
		   $j('input#event-recurrence').change(updateShowHideRecurrence);  
		   $j('input#rsvp-checkbox').change(updateShowHideRsvp);   
		// recurrency elements   
		   $j('input#recurrence-interval').keyup(updateIntervalDescriptor);
		   $j('select#recurrence-frequency').change(updateIntervalDescriptor);
		   $j('select#recurrence-frequency').change(updateIntervalSelectors);
			
			// hiding or showing notes according to their content	
	    	jQuery('.postbox h3').prepend('<a class="togbox">+</a> ');
	    	if(jQuery("textarea[@name=event_notes]").val()!="") {
			   jQuery("textarea[@name=event_notes]").parent().parent().removeClass('closed');
			}
			jQuery('#event_notes h3').click( function() {
	        	jQuery(jQuery(this).parent().get(0)).toggleClass('closed');
				
	    	});  
	
		
		});
		//]]>
	</script>
	  
<?php	
}
add_action ('admin_head', 'dbem_admin_general_script');                


// Google maps implementation
function dbem_map_script() {
	$gmap_is_active = get_option('dbem_gmap_is_active');  
		if ($gmap_is_active) { 
			if (strpos(get_option('dbem_single_event_format'), "#_MAP")) { // loading the script is useless unless #_MAP is in the format
			 
			if (isset($_REQUEST['event_id']) && $_REQUEST['event_id'] != '') { 
				 
				// single event page
				$event_ID=$_REQUEST['event_id'];
			    $event = dbem_get_event($event_ID);
				if ($event['venue_town'] != '') {
					$gmap_key = get_option('dbem_gmap_key'); 
					if($event['venue_address'] != "") {
				    	$search_key = $event['venue_address'].", ".$event['venue_town'];
					} else {
						$search_key = $event['venue_name'].", ".$event['venue_town'];
					}
				$map_text_format = get_option('dbem_map_text_format');
		    	$map_text = dbem_replace_placeholders($map_text_format, $event, "map");   
                
			?> 
   
	
			<script src="http://maps.google.com/maps?file=api&amp;v=2&amp;key=<?php echo $gmap_key;?>" type="text/javascript"></script>         
			<script type="text/javascript">
			    //<![CDATA[
				$j=jQuery.noConflict();
			    function loadMap() {
		      		if (GBrowserIsCompatible()) {
		        		var map = new GMap2(document.getElementById("event-map"));
		        		var mapTypeControl = new GLargeMapControl();
								var topRight = new GControlPosition(G_ANCHOR_TOP_RIGHT, new GSize(10,10));
							 	map.addControl(mapTypeControl, topRight);
								
							 // map.addControl(new GLargeMapControl()); 
								//map.setCenter(new GLatLng(37.4419, -122.1419), 13);   
						var geocoder = new GClientGeocoder();
						var address = "<?php echo $search_key ?>" ;
						geocoder.getLatLng(
						    address,
						    function(point) {
						      if (!point) {
						       	$j("#event-map").hide();
						      } else {
								mapCenter= new GLatLng(point.lat()+0.01, point.lng()+0.005);
						        map.setCenter(mapCenter, 13);
						        var marker = new GMarker(point);
						        map.addOverlay(marker);
						        marker.openInfoWindowHtml('<?php echo $map_text;?>');
						      }
						    }
						  );   
		      		}
		    	}
   
				$j(document).ready(function() {
		  		if ($j("#event-map").length > 0 ) {	
						loadMap();  
			      }
		 
			   }); 
			   $j(document).unload(function() {
						if ($j("#event-map").length > 0 ) {	 
							GUnload();
						}
			   });
			//]]>
			</script> 
			<style type="text/css">
			#event-map {
				width: 450px; 
				height: 300px;
			}
			#event-map img {
				background: transparent;
			}
			</style>
		<?php
		 		}
			} 
		}
	}
}        
add_action ('wp_head', 'dbem_map_script'); 

function dbem_admin_map_script() {  
	if ((isset($_REQUEST['event_id']) && $_REQUEST['event_id'] != '') || (isset($_REQUEST['page']) && $_REQUEST['page'] == 'venues')) {   
		if (!(isset($_REQUEST['action']) && $_REQUEST['action'] == 'dbem_delete')) {    
			// single event page    
			
	   	
			$event_ID=$_REQUEST['event_id'];
		    $event = dbem_get_event($event_ID);
			
			if ($event['venue_town'] != '' || (isset($_REQUEST['page']) && $_REQUEST['page'] = 'venues')) {
				$gmap_key = get_option('dbem_gmap_key');
		        if($event['venue_address'] != "") {
			    	$search_key = $event['venue_address'].", ".$event['venue_town'];
				} else {
					$search_key = $event['venue_name'].", ".$event['venue_town'];
				}
	   		
		?>
		<style type="text/css">
		   div#venue_town, div#venue_address, div#venue_name {
					width: 480px;
				}
				table.form-table {
					width: 50%;
				}
		</style>
		<script src="http://maps.google.com/maps?file=api&amp;v=2&amp;key=<?php echo $gmap_key;?>" type="text/javascript"></script>         
		<script type="text/javascript">
			//<![CDATA[
		   	$j=jQuery.noConflict();
		
			function loadMap(venue, town, address) {
	      		if (GBrowserIsCompatible()) {
	        		var map = new GMap2(document.getElementById("event-map"));
	        	//	map.addControl(new GScaleControl()); 
							//map.setCenter(new GLatLng(37.4419, -122.1419), 13);   
					var geocoder = new GClientGeocoder();
					if (address !="") {
						searchKey = address + ", " + town;
					} else {
						searchKey =  venue + ", " + town;
					}
					
					var search = "<?php echo $search_key ?>" ;
					geocoder.getLatLng(
					    searchKey,
					    function(point) {
					      if (!point) {
					       	$j("#event-map").hide();
							$j('#map-not-found').show();
					      } else {
							mapCenter= new GLatLng(point.lat()+0.01, point.lng()+0.005);
						    map.setCenter(mapCenter, 13);
					        var marker = new GMarker(point);
					        map.addOverlay(marker);
					        marker.openInfoWindowHtml('<strong>' + venue +'</strong><p>' + address + '</p><p>' + town + '</p>'); 
							$j('input#venue-latitude').val(point.y);
					        $j('input#venue-longitude').val(point.x);   
							$j("#event-map").show();
							$j('#map-not-found').hide();
							}
					    }
					  );   
	      	 //	map.addControl(new GSmallMapControl());
					 // map.addControl(new GMapTypeControl());
					
					 }
	    	}
   
			$j(document).ready(function() {
	  		eventVenue = $j("input#venue-name").val(); 
			  eventTown = $j("input#venue-town").val(); 
				eventAddress = $j("input#venue-address").val();
		   
				loadMap(eventVenue, eventTown, eventAddress);
			
				$j("input#venue-name").blur(function(){
						newEventVenue = $j("input#venue-name").val();  
						if (newEventVenue !=eventVenue) {                
							loadMap(newEventVenue, eventTown, eventAddress); 
							eventVenue = newEventVenue;
					   
						}
				});
				$j("input#venue-town").blur(function(){
						newEventTown = $j("input#venue-town").val(); 
						if (newEventTown !=eventTown) {  
							loadMap(eventVenue, newEventTown, eventAddress); 
							eventTown = newEventTown;
							} 
				});
				$j("input#venue-address").blur(function(){
						newEventAddress = $j("input#venue-address").val(); 
						if (newEventAddress != eventAddress) {
							loadMap(eventVenue, eventTown, newEventAddress);
						 	eventAddress = newEventAddress; 
						}
				});
			  
			
		 
		   }); 
		   $j(document).unload(function() {
				GUnload();
		   });
		    //]]>
		</script>
	<?php
	 		}
		}
}    
}
$gmap_is_active = get_option('dbem_gmap_is_active'); 
if ($gmap_is_active) {
	add_action ('admin_head', 'dbem_admin_map_script');
	  
}

// Script to validate map options
function dbem_admin_options_script() { 
	if (isset($_REQUEST['page']) && $_REQUEST['page'] == 'events-manager/events-manager.php') {  
	   ?>
	<script type="text/javascript">
	//<![CDATA[
		$j=jQuery.noConflict();
		
		 $j(document).ready(function() {
	  		    // users cannot enable Googlr Maps without an api key
				function verifyOptionsForm(){
				   	var gmap_is_active = $j("input[@name=dbem_gmap_is_active]:checked").val();
						var gmap_key = $j("input[@name=dbem_gmap_key]").val();
				  	if(gmap_is_active == '1' && (gmap_key == '')){
					    alert("<?php _e('You cannot enable Google Maps integration without setting an appropriate API key.');?>");
							$j("input[@name='dbem_gmap_is_active']:nth(1)").attr("checked","checked");
					
						return false;
					} else {
						return true;
					}
				}
				
        $j('#dbem_options_form').bind("submit", verifyOptionsForm);


		   });
	
		
		//]]>
	</script>
	
	<?php
		
	}
	
}
add_action ('admin_head', 'dbem_admin_options_script');   

function dbem_rss_link($justurl=false) {
	$rss_title = get_option('dbem_events_page_title');
	$url = get_bloginfo('url')."/?dbem_rss=main";  
	$link = "<a href='$url'>RSS</a>";
	if ($justurl)
		echo $url;
	else
		echo $link;
}  

function dbem_rss() {
	if (isset($_REQUEST['dbem_rss']) && $_REQUEST['dbem_rss'] == 'main') {	
		header("Content-type: text/xml");
		echo "<?xml version='1.0'?>\n";
		
		$events_page_id = get_option('dbem_events_page');
		$events_page_link = get_permalink($events_page_id);
		if (stristr($events_page_link, "?"))
		  $joiner = "&amp;";
		else
			$joiner = "?";
		
		
		?>
		<rss version="2.0">
		<channel>
		<title><?php echo get_option('dbem_rss_main_title');?></title>
    <link><?php echo $events_page_link; ?></link>
    <description><?php echo get_option('dbem_rss_main_description');?></description>
    <docs>http://blogs.law.harvard.edu/tech/rss</docs>
    <generator>Weblog Editor 2.0</generator>
    	<?php
			$title_format = get_option('dbem_rss_title_format');
			$description_format = str_replace(">","&gt;",str_replace("<","&lt;",get_option('dbem_rss_description_format')));
			$events = dbem_get_events(5);
			foreach ($events as $event) {
				$title = dbem_replace_placeholders($title_format, $event, "rss");
        		$description = dbem_replace_placeholders($description_format, $event, "rss");
				echo "<item>";   
				echo "<title>$title</title>\n";
				echo "<link>$events_page_link".$joiner."event_id=$event->event_id</link>\n ";
				echo "<description>$description </description>\n";
				echo "</item>";
      }
			?>

			</channel>
			</rss>
		</code>
	
	<?php
	die();
	}
}
add_action('init','dbem_rss');
function substitute_rss($data) {
	if (isset($_REQUEST['event_id'])) 
		return get_bloginfo('url')."/?dbem_rss=main";
	else
		return $data;
}           
function dbem_general_css() {  
	$base_url = get_bloginfo('url');
	echo "<link rel='stylesheet' href='$base_url/wp-content/plugins/events-manager/events_manager.css' type='text/css'/>";
	
}
add_action('wp_head','dbem_general_css');
add_action('admin_head','dbem_general_css');
//add_filter('feed_link','substitute_rss')
                
// TODO roba da mettere nell'ordine giusto
function dbem_delete_event($event_id) {
		global $wpdb;	
		$table_name = $wpdb->prefix.EVENTS_TBNAME;
		$sql = "DELETE FROM $table_name WHERE event_id = '$event_id';";
	 	$wpdb->query($sql);

}

?>